jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Check Chrome version
        run: google-chrome --version

      - name: Match Chromedriver to Chrome
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          echo "Installing Chromedriver $CHROMEDRIVER_VERSION"
          curl -o chromedriver.zip "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver.zip -d /usr/local/bin
          chmod +x /usr/local/bin/chromedriver

      - name: Check Chromedriver version
        run: chromedriver --version

      - name: Build and Test
        run: ./gradlew clean test
