name: Run E2E Tests

on:
  push

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
#
#      - name: Set up Chrome and Chromedriver
#        uses: nanasess/setup-chromedriver@v1
#        with:
#          chromedriver-version: 114.0.5735.90

      - name: Install a specific Chrome version
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable=114.0.5735.90

      - name: Install matching Chromedriver
        run: |
          curl -o chromedriver.zip "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip"
          unzip chromedriver.zip -d /usr/local/bin
          chmod +x /usr/local/bin/chromedriver

      - name: Print Chromedriver versions
        run: |
          google-chrome --version
          chromedriver --version

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle tests
        run: ./gradlew test
        env:
          BROWSER: chrome

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/tests/test
